# --- Stage 1: Build and test in Maven container ---
    FROM maven:3.9.6-eclipse-temurin-17 AS build

    ENV DEBIAN_FRONTEND=noninteractive
    
    # Install needed tools
    RUN apt-get update && apt-get install -y \
        git \
        curl \
        nodejs \
        npm \
        && apt-get clean \
        && rm -rf /var/lib/apt/lists/*
    
    # Set working directory
    WORKDIR /app
    
    # Copy entrypoint script and make it executable
  
   COPY pom.xml .

RUN mvn dependency:go-offline -B


    

COPY . .

#RUN chmod +x /app/entrypoint.sh
    
    # Default command
    #ENTRYPOINT ["/app/entrypoint.sh"]
    

    ENTRYPOINT ["/bin/bash", "-c", "\
    echo \"Starting selenium-test-runner container...\"; \
    echo \"--- Running Maven tests ---\"; \
    mvn test -DsuiteXmlFile=Suites/JustForTest.xml -X; \
    TEST_EXIT_CODE=$?; \
    echo \"-----------------------------------\"; \
    echo \"Tests finished with exit code: $TEST_EXIT_CODE\"; \
    echo \"Check reports at /app/Reports/CustomReport and /app/Reports/Screenshots\"; \
    echo \"-----------------------------------\"; \
    exit $TEST_EXIT_CODE \
"]
    CMD ["mvn", "test"]
    
	
	